Repository neanes/neanes, pull requests merged in 2023-11, with the labels that each got.

#388 feat: Update mac icons
  build/icons/icon.icns
Labels: feature

#416 chore: upgrade to vite 5
  package-lock.json
  package.json
  vite.config.mjs
Labels: dependencies

#429 Improve `heteronConnecting` anchor point
  docs/.vitepress/theme/assets/fonts/Neanes.otf
  src/assets/fonts/Neanes.otf
  src/assets/fonts/neanes.metadata.json
  src/models/PageSetup.ts
  src/models/save/v1/PageSetup.ts
Labels: enhancement
