Repository neanes/neanes, pull requests merged in 2024-06, with the labels that each got.

#726 Rich Text Headers and Footers
  src/components/Editor.vue
  src/components/PageSetupDialog.vue
  src/components/TextBox.vue
  src/components/TextBoxRich.vue
  src/i18n/en/dialog.json
  src/models/Element.ts
  src/models/PageSetup.ts
  src/models/save/v1/Element.ts
  src/models/save/v1/Footer.ts
  src/models/save/v1/Header.ts
  src/models/save/v1/PageSetup.ts
  src/services/LayoutService.ts
  src/services/SaveService.ts
Labels: Type: Feature, Component: Other

#729 Fix disappearing rich text content
  src/components/TextBoxRich.vue
Labels: Type: Bug, Component: Other

#738 Fix InputUnit handling of null values
  src/components/InputUnit.vue
Labels: Type: Bug

#739 Add custom width option for Drop Caps
  src/components/Editor.vue
  src/components/ToolbarDropCap.vue
  src/i18n/en/toolbar.json
  src/models/Element.ts
  src/models/save/v1/Element.ts
  src/services/LayoutService.ts
  src/services/SaveService.ts
Labels: Type: Feature, Component: Layout

#740 Add custom width to text box
  src/components/Editor.vue
  src/components/ToolbarTextBox.vue
  src/models/Element.ts
  src/models/save/v1/Element.ts
  src/services/LayoutService.ts
  src/services/SaveService.ts
Labels: Type: Feature, Component: Layout

#741 Add custom height to text box
  src/components/Editor.vue
  src/components/ToolbarTextBox.vue
  src/i18n/en/toolbar.json
  src/models/Element.ts
  src/models/save/v1/Element.ts
  src/services/LayoutService.ts
  src/services/SaveService.ts
Labels: Type: Feature, Component: Layout

#742 Add handles to drop caps
  src/components/DropCap.vue
Labels: Type: Feature, Component: Layout

#743 Fix inline text box bugs
  src/components/TextBox.vue
  src/services/LayoutService.ts
Labels: Type: Bug, Component: Layout

#744 Upgrade to Electron v30
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: Type: Dependencies

#750 Fix Greek melisma casing
  src/services/MelismaHelperGreek.test.ts
  src/services/MelismaHelperGreek.ts
Labels: Type: Bug, Component: Lyrics

#752 Add RTL support for rich text boxes
  src/components/Editor.vue
  src/components/TextBoxRich.vue
  src/components/ToolbarTextBoxRich.vue
  src/i18n/en/toolbar.json
  src/models/Element.ts
  src/models/save/v1/Element.ts
  src/services/SaveService.ts
Labels: Type: Feature, Component: Layout

#757 Allow apli on apostrofos ligatures
  src/models/NeumeReplacements.ts
Labels: Type: Feature, Component: Neumes

#766 Add break-after CSS to pages
  src/components/Editor.vue
Labels: Type: Bug, Component: Layout

#790 Bump `ckeditor5` from 41.4.2 to 42.0.0
  package-lock.json
  package.json
Labels: Type: Dependencies
