Repository neanes/neanes, pull requests merged in 2024-07, with the labels that each got.

#796 Fix dropcap toolbar causing blank page in PDF export.
  src/components/Editor.vue
Labels: Type: Bug, Component: Layout

#798 Fix drop cap alignment
  src/components/Editor.vue
  src/services/LayoutService.ts
  src/utils/TestFileGenerator.ts
  src/utils/TestFileType.ts
Labels: Type: Bug, Component: Layout

#803 Add special handling for macOS keyboard shortcuts
  src/components/Editor.vue
Labels: Type: Bug, Component: Electron

#804 Use font ascent to align drop caps even more precisely
  src/services/LayoutService.ts
  src/services/TextMeasurementService.ts
Labels: Type: Feature, Component: Layout

#805 Fix lyric redo kbd shortcut on macOS
  src/components/Editor.vue
Labels: Type: Bug

#808 Add more complex Zo attraction algorithm
  src/services/audio/PlaybackService.test.ts
  src/services/audio/PlaybackService.ts
Labels: Type: Feature, Component: Audio

#807 Upgrade NPM from 10.2.3 to 10.7.0
  package.json
Labels: Type: Dependencies

#810 Fix macOS edit shortcuts
  src/components/Editor.vue
Labels: Type: Bug, Component: Electron

#814 Fix measure bar jitters
  src/services/LayoutService.ts
Labels: Type: Bug, Component: Layout

#820 Fix focus bug for drop caps when lyrics are locked
  src/components/DropCap.vue
Labels: Type: Bug, Component: Other

#823 Disable ke attraction
  src/services/audio/PlaybackService.test.ts
  src/services/audio/PlaybackService.ts
Labels: Type: Bug, Component: Audio

#824 Fix keyboard docs
  docs/guide/keyboard.md
Labels: Type: Bug, Type: Documentation

#831 Upgrade CKEditor from 42.0.0 to 42.0.1
  package-lock.json
  package.json
  src/components/TextBoxRich.vue
  src/customEditor.ts
  vite.config.mjs
Labels: Type: Dependencies

#832 Remove unnecessary workaround
  package.json
Labels: Type: Dependencies

#834 Add high ni to the chromatic fthora note options
  docs/guide/index.md
  src/components/ToolbarMartyria.vue
  src/components/ToolbarNeume.vue
Labels: Type: Feature, Component: Neumes

#835 Allow zooming up to 500%
  src/components/Editor.vue
  src/components/ToolbarMain.vue
Labels: Type: Feature

#841 Reorganize CKEditor toolbar
  src/customEditor.ts
Labels: Type: Bug

#849 Split out contributing guide into a separate document
  CONTRIBUTING.md
  README.md
Labels: Type: Documentation

#836 Display an error message when invalid zoom is selected
  src/components/Editor.vue
  src/i18n/en/toolbar.json
Labels: Type: Bug

#864 Fix toolbar labels for general sharp and flat
  src/components/ToolbarNeume.vue
Labels: Type: Bug, Component: UI

#869 Fix missing melisama for running elaphron
  src/services/LyricService.test.ts
  src/services/LyricService.ts
Labels: Type: Bug, Component: Lyrics

#870 add support for all the chromatic fthora notes
  src/components/ToolbarMartyria.vue
  src/components/ToolbarNeume.vue
Labels: Type: Feature, Component: Neumes
