Repository neanes/neanes, pull requests merged in 2024-04, with the labels that each got.

#605 Add speed slider
  src/components/Editor.vue
  src/components/InputUnit.vue
  src/components/ToolbarMain.vue
  src/utils/Unit.ts
Labels: enhancement

#617 Multipanel text boxes
  src/components/Editor.vue
  src/components/TextBox.vue
  src/components/ToolbarTextBox.vue
  src/i18n/en/toolbar.json
  src/models/Element.ts
  src/models/Footer.ts
  src/models/Header.ts
  src/models/save/v1/Element.ts
  src/services/LayoutService.ts
  src/services/SaveService.ts
Labels: enhancement

#633 Advanced Lyrics Entry
  docs/guide/advanced.md
  docs/guide/images/guide-lyrics-toolbar-1.png
  docs/guide/images/guide-lyrics-toolbar-accept-1.png
  docs/guide/images/guide-lyrics-toolbar-blank-1.png
  docs/guide/images/guide-lyrics-toolbar-locked-1.png
  docs/guide/images/guide-lyrics-toolbar-locked-2.png
  docs/guide/images/guide-lyrics-toolbar-locked-3.png
  docs/guide/index.md
  electron/main/index.ts
  examples/English - Prosomia - With What Fair Crowns.byzx
  src/components/DropCap.vue
  src/components/Editor.vue
  src/components/FileMenuBar.vue
  src/components/ToolbarLyricManager.vue
  src/components/ToolbarNeume.vue
  src/i18n/en/menu.json
  src/i18n/en/toolbar.json
  src/ipc/ipcChannels.ts
  src/main.ts
  src/models/Element.ts
  src/models/LyricSetup.ts
  src/models/Staff.ts
  src/models/Workspace.ts
  src/models/save/v1/Element.ts
  src/models/save/v1/Score.ts
  src/services/LyricService.ts
  src/services/SaveService.ts
  src/services/history/CommandService.ts
Labels: feature

#642 Add Stathis Series font
  src/App.vue
  src/assets/fonts/Neanes.otf
  src/assets/fonts/NeanesRTL.otf
  src/assets/fonts/NeanesStathisSeries.metadata.json
  src/assets/fonts/NeanesStathisSeries.otf
  src/components/Editor.vue
  src/components/PageSetupDialog.vue
  src/services/FontService.ts
Labels: enhancement

#648 Ignore Electron 30+ as it segfaults on Linux
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: bug

#649 Set application category
  electron-builder.json
Labels: maintenance

#650 Improve wrapping for text boxes
  src/components/TextBox.vue
Labels: Type: Feature

#653 Adapt to issue tracker triage
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#654 Fix inline text box width calculation
  src/services/LayoutService.ts
Labels: Type: Bug

#655 Font-independent Melismata
  src/components/Editor.vue
  src/models/Element.ts
  src/models/PageSetup.ts
  src/services/LayoutService.ts
  src/services/TextMeasurementService.ts
  src/services/integration/ByzHtmlExporter.ts
Labels: Type: Bug, Type: Feature

#658 Add low martyriae
  src/components/ToolbarMartyria.vue
  src/components/ToolbarNeume.vue
  src/i18n/el/model.json
  src/i18n/en/model.json
  src/models/Neumes.ts
  src/models/Scales.ts
  src/models/save/v1/Neumes.ts
  src/models/save/v1/Scales.ts
  src/services/LayoutService.ts
  src/services/NeumeKeyboard.test.ts
  src/services/NeumeMappingService.ts
  src/services/audio/PlaybackService.ts
Labels: Type: Feature

#660 Look ahead past martyriae, drop caps, and mode keys
  src/services/LyricService.ts
Labels: Type: Bug

#659 Handle whole-word drop caps
  src/components/Editor.vue
  src/services/LyricService.ts
Labels: Type: Bug

#662 Improve examples
  examples/Arabic - RTL - Resurrectional Apolytikion - Plagal of the Fourth Mode.byzx
  examples/English - Lord I Have Cried - First Mode.byzx
  examples/English - Prosomia - With What Fair Crowns.byzx
  examples/Greek - Stathis Series - Let My Prayer.byzx
Labels: Type: Bug

#663 Correctly calculate note indicator for multi-neume spread
  src/services/LayoutService.ts
Labels: Type: Bug

#666 Revert "Handle whole-word drop caps"
  src/components/Editor.vue
  src/services/LyricService.ts
Labels: Type: Bug

#667 Fix lyric round-tripping bug
  src/services/LyricService.ts
Labels: Type: Bug

#668 Fix lyric height bug when using gorthmikon/pelastikon
  src/components/Editor.vue
  src/models/Element.ts
  src/services/LayoutService.ts
Labels: Type: Bug, Component: Lyrics

#669 Fix lyrics look-ahead logic
  src/services/LyricService.ts
Labels: Type: Bug, Component: Lyrics
