Repository neanes/neanes, pull requests merged in 2024-03, with the labels that each got.

#522 chore: bump electron-builder from 24.9.1 to 24.13.3
  package-lock.json
  package.json
Labels: maintenance, dependencies

#523 Lyric Search
  electron/main/index.ts
  src/assets/icons/arrow-down.svg
  src/assets/icons/arrow-up.svg
  src/assets/icons/x.svg
  src/components/Editor.vue
  src/components/FileMenuBar.vue
  src/components/SearchText.vue
  src/i18n/el/menu.json
  src/i18n/en/menu.json
  src/i18n/ro/menu.json
  src/ipc/ipcChannels.ts
  src/main.ts
  src/models/Element.ts
  src/services/LayoutService.ts
  src/services/TextSearchService.ts
Labels: enhancement, feature

#526 Add special characters to lyrics toolbar
  src/components/Editor.vue
  src/components/ToolbarLyrics.vue
  src/services/integration/ByzHtmlExporter.ts
  src/utils/constants.ts
Labels: enhancement, feature

#527 Default text box style
  src/components/Editor.vue
  src/components/PageSetupDialog.vue
  src/components/TextBox.vue
  src/components/ToolbarTextBox.vue
  src/i18n/en/dialog.json
  src/models/Element.ts
  src/models/PageSetup.ts
  src/models/save/v1/Element.ts
  src/models/save/v1/PageSetup.ts
  src/models/save/v1/Score.ts
  src/services/LayoutService.ts
  src/services/SaveService.ts
  src/services/integration/ByzHtmlExporter.ts
Labels: enhancement, feature

#553 Bump Electron from 28.1.4 to 28.2.6
  package-lock.json
  package.json
Labels: dependencies, javascript

#555 Bump `vue-draggable-resizable` from 2.3.0 to 3.0.0
  package-lock.json
  package.json
  src/components/ImageBox.vue
  src/main.ts
  src/shims-vue.d.ts
Labels: dependencies, javascript

#529 Missing vareia in example
  examples/English - Lord I Have Cried - First Mode.byzx
Labels: documentation

#559 chore: Update Vue to 3.4.21 in `package.json`
  package-lock.json
  package.json
Labels: dependencies, javascript

#560 chore: Bump Electron from 28.2.6 to 29.1.1
  package-lock.json
  package.json
Labels: dependencies, javascript

#561 Reverse connecting anchors for RTL font
  src/assets/fonts/NeanesRTL.otf
  src/assets/fonts/neanesrtl.metadata.json
Labels: bugfix

#562 Add virtual notes for ison
  src/models/Scales.ts
  src/services/audio/AnalysisService.ts
  src/services/audio/PlaybackService.ts
Labels: bugfix

#563 Show correct text for headers when printing
  examples/Arabic - RTL - Resurrectional Apolytikion - Plagal of the Fourth Mode.byzx
  src/components/Editor.vue
Labels: bugfix

#569 Fix heteron position for kentimata
  src/assets/fonts/Neanes.otf
  src/assets/fonts/NeanesRTL.otf
  src/assets/fonts/neanes.metadata.json
  src/assets/fonts/neanesrtl.metadata.json
Labels: bugfix

#578 Fix line height default value in html exporter.
  src/services/integration/ByzHtmlExporter.ts
Labels: bugfix

#598 Display playback time and BPM in main toolbar
  src/components/Editor.vue
  src/components/ToolbarMain.vue
  src/models/Workspace.ts
  src/services/audio/PlaybackService.ts
Labels: enhancement
