Repository neanes/neanes, pull requests merged in 2024-10, with the labels that each got.

#1012 Upgrade ESLint from 8.57.0 to 9.12.0
  .eslintrc.js
  .vscode/.debug.script.mjs
  docs/.vitepress/theme/index.js
  docs/components/Downloads.vue
  electron/main/index.ts
  electron/preload/index.ts
  eslint.config.mjs
  package-lock.json
  package.json
  src/components/Editor.vue
  src/registerServiceWorker.ts
  src/services/audio/AudioService.ts
  src/services/audio/PlaybackService.ts
  vite.config.mjs
Labels: Type: Dependencies

#1016 Only allow primary gorgons on hyporoe
  src/components/ToolbarNeume.vue
Labels: Type: Bug, Component: Neumes

#1020 Improve enharmonic martyria calculation
  src/services/LayoutService.ts
Labels: Type: Bug, Component: Neumes

#1036 Allow the chromatic note for secondary and tertiary fthora
  src/components/Editor.vue
  src/components/ToolbarNeume.vue
  src/models/Element.ts
  src/models/save/v1/Element.ts
  src/services/LayoutService.ts
  src/services/SaveService.ts
  src/services/audio/AnalysisService.ts
Labels: Type: Bug, Component: Neumes

#1051 Fix enharmonic playback
  src/services/audio/PlaybackService.ts
Labels: Type: Bug, Component: Audio

#1067 Add MusicXML export
  electron/main/index.ts
  src/components/Editor.vue
  src/components/ExportDialog.vue
  src/components/FileMenuBar.vue
  src/i18n/el/menu.json
  src/i18n/en/dialog.json
  src/i18n/en/menu.json
  src/i18n/ro/menu.json
  src/ipc/ipcChannels.ts
  src/main.ts
  src/services/audio/AnalysisService.ts
  src/services/integration/MusicXmlExporter.ts
  src/services/integration/MusicXmlModel.ts
  src/services/ipc/BrowserIpcService.ts
  src/services/ipc/IIpcService.ts
  src/services/ipc/IpcService.ts
Labels: Type: Feature, Component: Other

#1073 Fix ambitus and chronos alignment in mode key
  src/components/ModeKey.vue
Labels: Type: Bug, Component: Layout
