Repository neanes/neanes, pull requests merged in 2025-07, with the labels that each got.

#1548 Update `vite-plugin-inspect` to the latest version
  package-lock.json
  package.json
Labels: skip-changelog

#1561 Don't show unsaved changes for non-user initiated text box height changes
  src/components/Editor.vue
Labels: Type: Feature, Component: UI

#1563 Include line break when pasting martyria
  src/models/Element.ts
  src/services/LyricService.ts
Labels: Type: Feature, Component: Other

#1565 Revert "chore: bump vite-plugin-electron from 0.28.8 to 0.29.0 (#1111)"
  package-lock.json
  package.json
Labels: skip-changelog

#1567 Add missing spaceAfter value
  src/services/LayoutService.ts
Labels: Type: Bug, Component: Neumes

#1568 Fix jitter in main toolbar when playing audio
  src/components/ToolbarMain.vue
Labels: Type: Bug, Component: UI

#1580 Adapt to CKEditor 5 v46.0.0 changes
  src/components/TextBoxRich.vue
Labels: Type: Dependencies

#1584 Adjust fthora distance above martyria
  docs/.vitepress/theme/assets/fonts/Neanes.otf
  src/assets/fonts/Neanes.otf
  src/assets/fonts/NeanesRTL.otf
  src/assets/fonts/NeanesStathisSeries.otf
  src/assets/fonts/neanes.metadata.json
  src/assets/fonts/neanesrtl.metadata.json
  src/assets/fonts/neanesstathisseries.metadata.json
  src/utils/TestFileGenerator.ts
  src/utils/TestFileType.ts
Labels: Type: Feature, Component: Neumes

#1586 Fix fthora/barline overlap above martyria
  docs/.vitepress/theme/assets/fonts/Neanes.otf
  src/assets/fonts/Neanes.otf
  src/assets/fonts/NeanesRTL.otf
  src/assets/fonts/NeanesStathisSeries.otf
  src/assets/fonts/neanes.metadata.json
  src/assets/fonts/neanesrtl.metadata.json
  src/assets/fonts/neanesstathisseries.metadata.json
  src/components/NeumeBoxMartyria.vue
Labels: Type: Bug, Component: Neumes

#1587 Fix fthora/barline overlap above martyria
  docs/.vitepress/theme/assets/fonts/Neanes.otf
  src/assets/fonts/Neanes.otf
  src/assets/fonts/NeanesRTL.otf
  src/assets/fonts/NeanesStathisSeries.otf
  src/assets/fonts/neanes.metadata.json
  src/assets/fonts/neanesrtl.metadata.json
  src/assets/fonts/neanesstathisseries.metadata.json
Labels: Type: Bug, Component: Neumes

#1522 Add mode key for Plagal of First Mode as from Pa
  src/i18n/en/model.json
  src/models/ModeKeys.ts
  src/services/integration/MusicXmlExporter.ts
Labels: Type: Feature, Component: Neumes

#1626 Fix barline for running elaphron in MusicXML export
  src/services/integration/MusicXmlExporter.ts
Labels: Type: Bug
