Repository neanes/neanes, pull requests merged in 2025-02, with the labels that each got.

#1242 Revive CI build
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/publish-web.yml
  .github/workflows/publish.yml
  package.json
Labels: skip-changelog

#1243 Update transitive dependencies
  package-lock.json
Labels: skip-changelog

#1270 Export --byz-neume-font-family
  src/services/integration/ByzHtmlExporter.ts
Labels: Type: Feature, Component: Other

#1282 Add half-letter and half-legal page sizes
  electron/main/index.ts
  src/models/PageSetup.ts
  src/models/save/v1/PageSetup.ts
Labels: Type: Feature, Component: Layout

#1294 Add Latex Export
  electron/main/index.ts
  src/assets/fonts/Neanes.otf
  src/assets/fonts/NeanesRTL.otf
  src/assets/fonts/NeanesStathisSeries.otf
  src/assets/fonts/neanes.metadata.json
  src/assets/fonts/neanesrtl.metadata.json
  src/assets/fonts/neanesstathisseries.metadata.json
  src/components/Editor.vue
  src/components/ExportDialog.vue
  src/components/NeumeBoxMartyria.vue
  src/components/ToolbarDropCap.vue
  src/components/ToolbarMartyria.vue
  src/components/ToolbarModeKey.vue
  src/components/ToolbarNeume.vue
  src/components/ToolbarTempo.vue
  src/components/ToolbarTextBox.vue
  src/components/ToolbarTextBoxRich.vue
  src/i18n/en/dialog.json
  src/i18n/en/menu.json
  src/i18n/en/toolbar.json
  src/ipc/ipcChannels.ts
  src/main.ts
  src/models/Element.ts
  src/models/PageSetup.ts
  src/models/save/v1/Element.ts
  src/services/FontService.ts
  src/services/LayoutService.ts
  src/services/SaveService.ts
  src/services/integration/LatexExporter.ts
  src/services/ipc/BrowserIpcService.ts
  src/services/ipc/IIpcService.ts
  src/services/ipc/IpcService.ts
Labels: Type: Feature, Component: Other
